@baseurl = http://localhost:5000/api

###
POST {{baseurl}}/auth/register
Content-Type: application/json

{
    "username": "Filo",
    "email": "phil@gmail.com",
    "password": ""
}

###
POST {{baseurl}}/auth/login
Content-Type: application/json

{
    "email": "phil@gmail.com",
    "password": ""
}