
@baseurl = http://localhost:5000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTE4NmFjZGU4MzJkYWZhODc5NGRiNzAiLCJpYXQiOjE3Nzk5ODUxMDEsImV4cCI6MTc4MDU4OTkwMX0.kSKS4yRmMZfhgupdPxYnZLOqN3XyXZ0T8htzw-RA8gI
@id = 6a13d6c77a6fd036c2740424


###
POST {{baseurl}}/auth/register
Content-Type: application/json

{
    "username": "Filo",
    "email":"philshou@gmail.com",
    "password": "asdfasdf"
}

###
POST {{baseurl}}/auth/login
Content-Type: application/json

{
    "email": "philshou@gmail.com",
    "password": "asdfasdf"
}

###
GET {{baseurl}}/users

###
DELETE {{baseurl}}/users/{{id}}
Authorization: Bearer {{token}}

###
PUT {{baseurl}}/users/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username":"Phillipe"
}
