@baseurl = http://localhost:5000/api

@apWorldGroupId = 69ec05cebe4e4e5e9626915d
@roommates343GroupId = 69ec05d0be4e4e5e9626915f

###Create AP world group
POST {{baseurl}}/groups
Content-Type: application/json

{
    "groupName": "AP world"
}

###Create Roommates group
POST {{baseurl}}/groups
Content-Type: application/json

{
    "groupName": "Roommates 343",
    "groupGoal": "We promise to complete our chores on time"
}

###Get all groups
GET {{baseurl}}/groups

###Get AP World group
GET {{baseurl}}/groups/{{apWorldGroupId}}

###Get Roommates 343 group
GET {{baseurl}}/groups/{{roommates343GroupId}}

###Update AP world
PUT {{baseurl}}/groups/{{apWorldGroupId}}
Content-Type: application/json

{
    "groupGoal": "Finish our ap world project"
}

###Delete AP world group
DELETE {{baseurl}}/groups/{{apWorldGroupId}}

###Delete Roommates 343 group
DELETE {{baseurl}}/groups/{{roommates343GroupId}}