@baseurl = http://localhost:5000/api


### Create user File
POST {{baseurl}}/users
Content-Type: application/json

{
    "googleId": "21341i233",
    "username": "File",
    "email": "philshou@gmail.com"
}

### Create user Demon1
POST {{baseurl}}/users
Content-Type: application/json

{
    "googleId": "o2i3nfd",
    "username": "demon1",
    "email": "demon@gmail.com"
}

### Get all users file
GET {{baseurl}}/users

### Get user by id file
GET {{baseurl}}/users/69d6f261269dbbe7880f888f

###Get user by id demon1
GET {{baseurl}}/users/69d6f2e4269dbbe7880f8895

### Update File to FILO
PUT {{baseurl}}/users/69d6f261269dbbe7880f888f
Content-Type: application/json

{
    "username": "FILO"
}

###